#!/bin/bash
#===============================================================================
#
#          FILE:  install
#
#         USAGE:  ./install
#
#   DESCRIPTION:  Installs the creamsn0w bundle.
#
#        AUTHOR:  Sorin Ionescu <sorin.ionescu@gmail.com>
#       VERSION:  1.0.1
#       CREATED:  2009-07-27 14:47:29-04:00
#===============================================================================


BUNDLE_NAME="creamsn0w"
BUNDLE="${BUNDLE_NAME}.bundle"
INSTALL_PATH="$( echo ~ )/Library/Application Support/PwnageTool/CustomPackages"
BUNDLE_ROOT=$BUNDLE/files
CARRIER_SUPPORT_PATH="${BUNDLE_ROOT}/System/Library/Carrier Bundles"

temp_ifs=$IFS
IFS=$'\n'
cd $( dirname $0 )

unzip -qq $BUNDLE

echo Building ${BUNDLE_NAME}.

# iPhone Carrier Support files.
if [[  $( find addons -type f -name '*.ipcc' ) ]]
then
	for ipcc in addons/*.ipcc
	do
		ipcc_name=$( echo $ipcc | sed -e 's/addons\///g' )
		echo "  Embedding ${ipcc_name}"
		unzip -qq ${ipcc} -d $ipcc_name
		mkdir -p $CARRIER_SUPPORT_PATH
		mv $ipcc_name/Payload/* $CARRIER_SUPPORT_PATH/
		rm -rf $ipcc_name
	done
fi

# Extracted deb package.
if [[  $( find addons -type f -name '*.zip' ) ]]
then
	for package in addons/*.zip
	do
		package_name=$( echo $package | sed -e 's/addons\///g' )
		echo "  Embedding ${package_name}"
		unzip -qq $package -d $package_name
		ditto $package_name $BUNDLE_ROOT
		rm -rf $package_name
	done
fi

# Update bundle size.
cd $BUNDLE
size=$( du -bcs | awk '{ print $1 }' | tail -n 1 )
PlistBuddy -c "Set :Size ${size}" Info.plist
cd ..

# Remove those pesky .DS_Store files.
find . -type f -name '.DS_Store' -delete

# redsn0w hack
redsn0w_path=$( mdfind 'redsn0w' | grep '\.app$' )
if [[ -n $redsn0w_path  ]]
then
	icy_path=$redsn0w_path/Contents/MacOS
	cd $BUNDLE/files
	tar czvf ../../Icy.tar.gz * &> /dev/null
	cd ../..
	if [[ ! -e "${icy_path}/Icy.tar.gz.bak" ]]
	then
		cd $icy_path
		mv Icy.tar.gz Icy.tar.gz.bak
		cd $( dirname $0 )
	fi
	mv -f Icy.tar.gz $icy_path
fi

echo "Installing $BUNDLE_NAME."
mkdir -p $INSTALL_PATH
rm -rf ${INSTALL_PATH}/${BUNDLE}
mv $BUNDLE $INSTALL_PATH/
echo Done.
IFS=$temp_ifs
