#!/bin/bash
#===============================================================================
#
#          FILE:  install
#
#         USAGE:  ./install
#
#   DESCRIPTION:  Installs the creamsn0w bundle.
#
#        AUTHOR:  Sorin Ionescu <sorin.ionescu@gmail.com>
#       VERSION:  1.0.2
#       CREATED:  2009-07-29 15:00:29-04:00
#===============================================================================


BUNDLE_NAME="creamsn0w"
BUNDLE="${BUNDLE_NAME}.bundle"
INSTALL_PATH="$( echo ~ )/Library/Application Support/PwnageTool/CustomPackages"
BUNDLE_ROOT=$BUNDLE/files
CARRIER_SUPPORT_PATH="${BUNDLE_ROOT}/System/Library/Carrier Bundles"

temp_ifs=$IFS
IFS=$'\n'
cd $( dirname $0 )

unzip -qq $BUNDLE

echo Building ${BUNDLE_NAME}.

for package in $( find addons -type f )
do
	case $package in
		*.ipcc)
			package_name=$( echo $package | sed -e 's/addons\///g' )
			dir_name=$( echo $package_name | sed -e 's/\(.*\)\..*$/\1/g' )
			echo "  Embedding ${package_name}"
			unzip -qq ${package} -d $dir_name
			mkdir -p $CARRIER_SUPPORT_PATH
			ditto $dir_name/Payload/ $CARRIER_SUPPORT_PATH/
			;;
		*.deb)
			package_name=$( echo $package | sed -e 's/addons\///g' )
			dir_name=$( echo $package_name | sed -e 's/\(.*\)\..*$/\1/g' )
			echo "  Embedding ${package_name}"
			mkdir -p $dir_name/Payload
			cd $dir_name
			ar x ../$package
			tar xzf data.tar.gz -C Payload
			cd ..
			ditto $dir_name/Payload $BUNDLE_ROOT/
			;;
		*.zip)
			package_name=$( echo $package | sed -e 's/addons\///g' )
			dir_name=$( echo $package_name | sed -e 's/\(.*\)\..*$/\1/g' )
			echo "  Embedding ${package_name}"
			unzip -qq $package -d $dir_name
			ditto $dir_name/ $BUNDLE_ROOT/
			;;
		*.tar.gz|*.tgz)
			package_name=$( echo $package | sed -e 's/addons\///g' )
			dir_name=$( echo $package_name | sed -e 's/\(.*\)\..*$/\1/g' )
			echo "  Embedding ${package_name}"
			mkdir $dir_name
			tar xzf $package -C $dir_name
			ditto $dir_name/ $BUNDLE_ROOT/
		;;
	esac
	rm -rf $dir_name
done

# Update bundle size.
cd $BUNDLE
size=$( echo "$( du -kcs | tail -n 1 | awk '{ print $1 }' ) * 1024" | bc -l )
PlistBuddy -c "Set :Size ${size}" Info.plist
cd ..

# Remove those pesky .DS_Store files and __MACOSX directories.
find . -type f -name '.DS_Store' -delete
find . -type d -name '__MACOSX' -exec rm -rf "{}" \; &> /dev/null

# redsn0w hack
redsn0w_path=$( mdfind 'redsn0w' | grep '\.app$' )
if [[ -n $redsn0w_path  ]]
then
	icy_path=$redsn0w_path/Contents/MacOS
	cd $BUNDLE/files
	tar czvf ../../Icy.tar.gz * &> /dev/null
	cd ../..
	if [[ ! -e "${icy_path}/Icy.tar.gz.bak" ]]
	then
		cd $icy_path
		mv Icy.tar.gz Icy.tar.gz.bak
		cd $( dirname $0 )
	fi
	mv -f Icy.tar.gz $icy_path
fi

echo "Installing $BUNDLE_NAME."
mkdir -p $INSTALL_PATH
rm -rf ${INSTALL_PATH}/${BUNDLE}
mv $BUNDLE $INSTALL_PATH/
echo Done.
IFS=$temp_ifs
