#!/bin/bash
#===============================================================================
#   DESCRIPTION:  Unistalls the creamsn0w bundle.
#        AUTHOR:  Sorin Ionescu (SpookyET) <sorin.ionescu@gmail.com>
#       VERSION:  1.0.3
#===============================================================================
install_path="$( echo ~ )/Library/Application Support/PwnageTool/CustomPackages"
bundle_name=creamsn0w
bundle="${bundle_name}.bundle"
temp_ifs=$IFS
IFS=$'\n'
echo Uninstalling ${bundle_name}.
rm -rf ${install_path}/${bundle}
echo Done.
IFS=$temp_ifs
