#!/bin/bash
#===============================================================================
#   DESCRIPTION:  Uninstalls the creamsn0w bundle.
#        AUTHOR:  Sorin Ionescu <sorin.ionescu@gmail.com>
#       VERSION:  1.0.4
#===============================================================================
install_path="$HOME/Library/Application Support/PwnageTool/CustomPackages"
bundle_name=creamsn0w
echo "Uninstalling ${bundle_name}."
find "${install_path}" -depth 1 -type d -name "*${bundle_name}*" -print0 | xargs -0 -I"{}" rm -rf "{}" 
echo Done.
